server:
  port: 8379

spring:
  application:
    name: es-server
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bool-exam?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root123

  # Redis配置
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 000000
    timeout: 5000
